### ISSUE TITLE
Add support for SSL Connections

### ISSUE THREAD

**Issue by jbenassi** [yugabyte/hashicorp-vault-ysql-plugin#8]
**Is your feature request related to a problem? Please describe.**
We are evaluating using Yugabyte and are using the hosted cloud offering. It looks like this plugin does not support connections using SSL mode. Unfortunately the cloud instances can only be connected via SSL mode using a cert. We would like to use this plugin for providing general access.

**Describe the solution you'd like**
Add support for SSL mode

**Comment by HarshDaryani896** [comment]
Thank you for the feature request.
Will look into it and get back to you in some time.

**Comment by HarshDaryani896** [comment]
Resolved in release [v1.2.0](https://github.com/yugabyte/hashicorp-vault-ysql-plugin/releases/tag/v1.2.0)
